from turtle import Turtle
def rec():
    bob=Turtle()
    bob.forward(200)
    bob.left(90)
    bob.forward(100)
    bob.left(90)
    bob.forward(200)
    bob.left(90)
    bob.forward(100)
    bob.left(90)
    bob.forward(100)
    bob.left(90)
    bob.forward(100)
rec()
